name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: ${{ matrix.check_name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - check_name: Tests (Ubuntu)
            os: ubuntu-latest
            python-version: "3.12"
            dependency_group: test-full
            run_doctests: true
          - check_name: Tests (Windows)
            os: windows-latest
            python-version: "3.13"
            dependency_group: dev
            run_doctests: false
          - check_name: Tests (macOS)
            os: macos-latest
            python-version: "3.14"
            dependency_group: dev
            run_doctests: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install . --group ${{ matrix.dependency_group }}

      - name: Run tests
        run: python -m pytest

      - name: Run doctests
        if: matrix.run_doctests
        run: python -m pytest -p scipy_doctest --doctest-modules --pyargs fatqat
